"""add ai_model_configs table

Revision ID: 6fcfed94bf9a
Revises: 11a5bdea170c
Create Date: 2026-03-31 17:24:51.248326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fcfed94bf9a'
down_revision: Union[str, Sequence[str], None] = '11a5bdea170c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=30), nullable=False),
    sa.Column('hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights_path', sa.String(length=512), nullable=True),
    sa.Column('is_trained', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("model_type IN ('linear', 'dense_nn')", name='ck_ai_model_configs_model_type'),
    sa.CheckConstraint("target IN ('final_grade', 'pass_probability')", name='ck_ai_model_configs_target'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_model_configs')
    # ### end Alembic commands ###
